stages:
    - test

default:
  image: ghcr.io/ml4gw/pinto:main 

variables:
    PRE_COMMIT_AUTO_FIX: "false"

include:
  remote: 'https://gitlab.com/yesolutions/gitlab-ci-templates/raw/main/templates/pre-commit-autofix.yaml'

injection-test:
    stage: test
    variables:
        test_dir: $CI_PROJECT_DIR/projects/injection_analysis/ 
    script: pinto run $test_dir pytest $test_dir/tests

background-test:
    stage: test
    variables:
        test_dir: $CI_PROJECT_DIR/projects/background_analysis/ 
    script: pinto run $test_dir pytest $test_dir/tests
